FROM node:20 AS build

WORKDIR /react-app

COPY package*.json .

RUN npm i

COPY public/ public

COPY src/ src

RUN npm run build

FROM httpd:alpine

WORKDIR /var/www/html

COPY --from=build /build/build/ .
