FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["fastapi", "dev", "api.py", "--host", "0.0.0.0"]