
# Stage build
FROM node:20 AS build
WORKDIR /react-app
COPY package*.json .
COPY check-node-version.js .
RUN npm i
COPY . .
RUN npm run build

# Stage release
FROM ngnix:1.25.5
WORKDIR /usr/share/ngnix/html
RUN rm -rf ./*
COPY --from=build /react-app/build .
ENTRYPOINT ["ngnix", "-g", "daemon off"]

# Stage release 2
# FROM httpd:alpine
# WORKDIR /var/www/html
# COPY --from=build /react-app/build/ .
