FROM python:3.9-slim

WORKDIR /app

# RUN apt-get -y install mesa-libGL

RUN apt update && apt install -y libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD ["fastapi", "dev", "api.py"]